### ISSUE TITLE
Add whitenoise to serve static assets

### ISSUE THREAD

**Issue by etrepum** [MissionBit/MB_Portal#10]
Here's some information for how we could do that (shouldn't be much different if deployed elsewhere): https://devcenter.heroku.com/articles/django-assets

This way we can have the logo, CSS, etc. all served with this project without having to go through much trouble.

**Comment by tylerIams** [comment]
Resolved in 83fc8dd891d1405529b49bb5d28880e63b071092

**Comment by etrepum** [comment]
"resolved in" comments should be done with PR numbers so that the issue gets closed when the PR is merged

**Comment by etrepum** [comment]
It's more common to do it the other way around, e.g. the PR that addresses this will say `Resolves #10`

**Comment by tylerIams** [comment]
Got it and will do
