### ISSUE TITLE
Duplicate account resolution

### ISSUE THREAD

**Issue by etrepum** [MissionBit/MB_Portal#11]
Follow-up to #8 

According to the comments in `register_after_oauth` it sounds like we delete the existing user record if they login with gmail. That sounds like a dangerous operation, since the existing user might have some data associated with it.

https://github.com/MissionBit/MB_Portal/blob/ec4f5a31288a7f93d7bd64b8dce93bdbb58f48a6/home/views.py#L105-L114

Ideally we would associate the new gmail login with the old existing user (and future logins should be associated with this record), we can be certain that the new gmail user does not have any other data associated with it as it was just created.

**Comment by tylerIams** [comment]
Resolved
