### ISSUE TITLE
Handle username collisions

### ISSUE THREAD

**Issue by etrepum** [MissionBit/MB_Portal#12]
We can't be certain that the user's full name is going to be unique, so we'll need ways to ensure that we can automatically generate a unique username for each person. We don't currently expose this username anywhere, so something random enough to avoid collisions may even suffice.

https://github.com/MissionBit/MB_Portal/blob/ec4f5a31288a7f93d7bd64b8dce93bdbb58f48a6/staff/staff_views_helper.py#L12-L23

**Comment by tylerIams** [comment]
I think the best way will be to check whether a username is taken, and if so, concatenate a number to it, check again, and repeat until it is unique.

**Comment by tylerIams** [comment]
Added fix in f0f8c8fc6e31bfe886e1be1c4596abe2253affa0
