### ISSUE TITLE
More robust birthdate parsing

### ISSUE THREAD

**Issue by etrepum** [MissionBit/MB_Portal#13]
The date parsing in here seems pretty fragile and it looks like the variable name `birthdate_d` is the month and `birthdate_m` is the day, which is a bit strange. I haven't looked at the form yet to see what sort of invalid input can be generated, but the parsing code here could use some work either way.

https://github.com/MissionBit/MB_Portal/blob/ec4f5a31288a7f93d7bd64b8dce93bdbb58f48a6/staff/staff_views_helper.py#L26-L30

**Comment by tylerIams** [comment]
Done
