### ISSUE TITLE
Create fall-throughs for invalid forms

### ISSUE THREAD

**Issue by tylerIams** [MissionBit/MB_Portal#24]
Use the technique described to create fall throughs for invalid forms rather than redirecting to avoid information loss:

https://stackoverflow.com/questions/14647723/django-forms-if-not-valid-show-form-with-error-message/14647770

**Comment by etrepum** [comment]
Also related, the site doesn't provide any context for what exactly went wrong for a given form submission. It's not even logged to the console. It's really hard to know what you did wrong without more precise feedback than "your form was not valid". Typically form validation will have relevant error messages for the form as a whole and mark relevant fields as invalid (if relevant) so you know where to start. Django forms probably already does this if you don't redirect away.
