### ISSUE TITLE
Make sure to use at least bootstrap version 4

### ISSUE THREAD

**Issue by tylerIams** [MissionBit/MB_Portal#26]
In templates, make sure to use version 4 of bootstrap, this will be complete when: 

- [ ] All templates use at least version 4 of bootstrap

**Comment by etrepum** [comment]
I did notice that there's a lot of redundancy across the templates, including the script and style dependencies. We should probably have all of the common stuff in one template that the other ones are all based on so that this is easier to maintain.

**Comment by etrepum** [comment]
It's also possible to do this without Bootstrap at all. For more complex pre-built components or a unified style you might consider something like [MDL](https://getmdl.io/) or [MUI](https://www.muicss.com/) instead.

**Comment by etrepum** [comment]
https://designsystem.digital.gov/ is worth a look too

**Comment by tylerIams** [comment]
We like MUI, trying that first
