### ISSUE TITLE
Avoid "N+1 query problem" by using "__in" instead of loops

### ISSUE THREAD

**Issue by etrepum** [MissionBit/MB_Portal#27]
In many cases we have code that looks like this:

```python
rows = []
for model_id in identifiers:
    rows.append(Model.objects.get(id=model_id))
```

This is a very common issue with software that uses a databases and it leads to performance problems because this requires N roundtrips to the database. It gets exponentially worse as the loops can be nested (often in a less obvious way by one method calling another in a loop).

Ideally, each method should have some constant bound for the number of queries it will ever do (particularly in terms of SELECT, with ORMs it can be more complicated to deal with INSERT, UPDATE, or DELETE). The following code will do at most one query to the database:

```python
rows = list(Model.objects.filter(id__in=identifiers))
```

https://docs.djangoproject.com/en/2.2/ref/models/querysets/#in

**Comment by tylerIams** [comment]
Thank you for this info.   I tried to tackle as much of it as I could in 9654574af9181255b49167581e1c473fa8f7d420 but I think there's still a lot more to be done on this front.  I also implemented Model.objects.bulk_create()(https://docs.djangoproject.com/en/2.2/ref/models/querysets/)  which I read only makes one database call while batch creating entries.

**Comment by etrepum** [comment]
I was hoping that this would get implemented in a separate PR so we could merge the other one sooner than later :)
